// <auto-generated />
using System;
using Kinvo.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kinvo.Infra.Data.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    partial class ProdutoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kinvo.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AtivoSigla")
                        .HasColumnName("AtivoSigla")
                        .HasMaxLength(8);

                    b.Property<int>("CategoriaProduto")
                        .HasColumnName("CategoriaProduto");

                    b.Property<DateTime?>("DataAtu");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnName("DataInicio");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasColumnName("Instituicao")
                        .HasMaxLength(30);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasMaxLength(50);

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnName("PrecoCompra");

                    b.Property<int?>("Qtde")
                        .IsRequired()
                        .HasColumnName("Qtde");

                    b.Property<decimal?>("TaxaAnual")
                        .HasColumnName("TaxaAnual");

                    b.Property<decimal?>("TaxaCorretagem")
                        .HasColumnName("TaxaCorretagem");

                    b.HasKey("Id");

                    b.ToTable("produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
